spring.application.name=betslip
spring.datasource.url=jdbc:postgresql://localhost:5432/betslip
spring.datasource.username=betslip
spring.datasource.password=betslip
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Kafka

# address of the kafka broker
spring.kafka.bootstrap-servers=localhost:9092 
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer

# Kafka messages have 2 parts to a message: key (optional), value (actual content) Convert into bytes 
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer