spring.application.name=betslip
spring.datasource.url=jdbc:postgresql://localhost:5432/betslip
spring.datasource.username=betslip
spring.datasource.password=betslip
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true