package io.sushant.betslip;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

@Entity
@Table(name = "bets")

public class Bet {

    @Id 
    @GeneratedValue(strategy = GenerationType.IDENTITY)   // auto generated by DB
    private Long id;           // primary key for the bets table in DB

    private String market;
    private String selection;  // Team or player
    private double stake;      //how much money has the person betting
    private double odds;
    private String status;     // Pending, Won or Lost

    public Bet () {
    }

    public Bet(String market, String selection, double stake, double odds) {
        this.market = market;
        this.selection = selection;
        this.stake = stake;
        this.odds = odds;
        this.status = "PENDING";   // every new bet starts as PENDING
    }

    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public String getMarket() { return market; }
    public void setMarket(String market) { this.market = market; }

    public String getSelection() { return selection; }
    public void setSelection(String selection) { this.selection = selection; }

    public double getStake() { return stake; }
    public void setStake(double stake) { this.stake = stake; }

    public double getOdds() { return odds; }
    public void setOdds(double odds) { this.odds = odds; }

    public String getStatus() { return status; }
    public void setStatus(String status) { this.status = status; }


}